2022-04-28 23:58:19,782 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:63] - ERROR: malformed node or string: <_ast.Name object at 0x00000172019C97F0>
2022-04-29 00:10:30,162 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1490] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' ([WinError 10053] 你的主机中的软件中止了一个已建立的连接。)")
2022-04-29 00:24:39,267 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:69] - ERROR: encryptData_ECB() missing 1 required positional argument: 'plain_text'
2022-04-29 00:24:39,267 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:69] - ERROR: encryptData_ECB() missing 1 required positional argument: 'plain_text'
2022-04-29 00:25:31,207 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:69] - ERROR: encryptData_ECB() missing 1 required positional argument: 'self'
2022-04-29 00:25:31,207 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:69] - ERROR: encryptData_ECB() missing 1 required positional argument: 'self'
2022-04-29 00:26:30,390 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:69] - ERROR: 'NoneType' object has no attribute 'encode'
2022-04-29 00:26:30,390 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:69] - ERROR: 'NoneType' object has no attribute 'encode'
2022-04-29 00:27:27,679 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:69] - ERROR: 'NoneType' object has no attribute 'encode'
2022-04-29 00:27:27,679 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:69] - ERROR: 'NoneType' object has no attribute 'encode'
2022-04-29 22:59:10,804 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1510] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-04-29 23:04:37,358 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1510] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-04-29 23:04:58,934 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1510] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-04-29 23:05:19,498 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:41] - ERROR: malformed node or string: <_ast.Name object at 0x00000226C8C85F70>
2022-04-29 23:05:19,498 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:41] - ERROR: malformed node or string: <_ast.Name object at 0x00000226C8C85F70>
2022-04-29 23:10:10,553 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1523] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-04-30 09:05:15,004 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:754] - ERROR: (1030, 'Got error 28 from storage engine')
2022-04-30 09:05:15,004 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:754] - ERROR: (1030, 'Got error 28 from storage engine')
2022-04-30 09:05:38,394 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:754] - ERROR: (1030, 'Got error 28 from storage engine')
2022-04-30 09:05:38,394 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:754] - ERROR: (1030, 'Got error 28 from storage engine')
2022-04-30 10:38:24,947 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:754] - ERROR: (1030, 'Got error 28 from storage engine')
2022-04-30 10:38:24,947 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:754] - ERROR: (1030, 'Got error 28 from storage engine')
2022-04-30 11:05:59,268 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1525] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' (timed out)")
2022-04-30 11:30:29,262 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1525] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' (timed out)")
2022-04-30 11:30:54,655 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1525] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' (timed out)")
2022-04-30 11:31:12,172 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1525] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' (timed out)")
2022-04-30 11:52:48,860 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:561] - ERROR: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
2022-04-30 11:52:48,860 - G:\毕设项目\my-graduate-project\API\appTest\pc_api\views.py[line:561] - ERROR: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
2022-04-30 17:41:09,328 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1525] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' (timed out)")
2022-04-30 17:55:33,580 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1533] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' (timed out)")
2022-05-01 12:06:56,539 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1643] - ERROR: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FeeItemCode': 'TJ008'}'' at line 3")
2022-05-01 12:06:56,539 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1643] - ERROR: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FeeItemCode': 'TJ008'}'' at line 3")
2022-05-01 12:06:56,539 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1643] - ERROR: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FeeItemCode': 'TJ008'}'' at line 3")
2022-05-01 12:08:03,571 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1644] - ERROR: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FeeItemCode': 'TJ008'}'' at line 3")
2022-05-01 12:08:03,571 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1644] - ERROR: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FeeItemCode': 'TJ008'}'' at line 3")
2022-05-01 12:08:03,571 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1644] - ERROR: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FeeItemCode': 'TJ008'}'' at line 3")
2022-05-01 12:48:12,524 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1558] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' (timed out)")
2022-05-01 12:48:33,062 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1558] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' (timed out)")
2022-05-01 12:48:33,062 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1558] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' (timed out)")
2022-05-01 13:34:27,025 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1571] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' ([WinError 10065] 套接字操作尝试一个无法连接的主机。)")
2022-05-01 13:34:27,025 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1571] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' ([WinError 10065] 套接字操作尝试一个无法连接的主机。)")
2022-05-01 13:34:27,025 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1571] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' ([WinError 10065] 套接字操作尝试一个无法连接的主机。)")
2022-05-01 13:34:51,662 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1571] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' ([WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。)")
2022-05-01 13:34:51,662 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1571] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' ([WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。)")
2022-05-01 13:34:51,662 - G:\毕设项目\my-graduate-project\API\appTest\utils\dbV3\db.py[line:1571] - ERROR: (2003, "Can't connect to MySQL server on '43.138.188.22' ([WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。)")
