2022-03-13 12:49:15,230 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:844] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 12:50:05,404 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:844] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 12:50:34,894 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:844] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 12:50:57,890 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:844] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 12:51:32,765 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:844] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 12:52:27,716 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:844] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 12:53:53,085 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:844] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 13:12:18,779 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:847] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 13:36:15,109 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:851] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 13:36:40,074 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:851] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 13:37:01,523 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:851] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 13:37:49,815 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:851] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 13:38:13,789 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:851] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 13:38:40,424 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:902] - ERROR: too many values to unpack (expected 2)
2022-03-13 13:38:40,424 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:902] - ERROR: too many values to unpack (expected 2)
2022-03-13 13:41:03,143 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:904] - ERROR: too many values to unpack (expected 2)
2022-03-13 13:41:03,143 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:904] - ERROR: too many values to unpack (expected 2)
2022-03-13 13:43:04,032 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:903] - ERROR: too many values to unpack (expected 2)
2022-03-13 13:43:04,032 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:903] - ERROR: too many values to unpack (expected 2)
2022-03-13 13:58:57,483 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:866] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 13:59:08,221 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:866] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 14:09:41,847 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:876] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 14:09:53,904 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:876] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 14:15:54,930 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:876] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 14:16:44,402 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:876] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 14:16:54,421 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:876] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 14:17:12,496 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:876] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 23:03:41,839 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:876] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 23:04:05,897 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:876] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-13 23:04:16,172 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:876] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-14 00:03:27,876 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:897] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
2022-03-14 00:03:47,694 - G:\毕设项目\API\appTest\utils\dbV3\db.py[line:897] - ERROR: (2003, "Can't connect to MySQL server on '120.77.44.219' (timed out)")
